# Site settings
title: Adrià Labay Mora
email: adria.labay@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  CV and some thoughts
summary: |
  Passionated by Physics, gradutated at the Autonomous University of Barcelona in 2019, with a strong enthusiasm for the fundations of Quantum Mechanics and its applications in the new era of technology, wishing to understand someday what is $$\psi$$. Curious about other areas of physics like High Energy, Quantum Gravity or Complex Systems, even other topics like psicology or phylosophy.

  Solid background in programming languages like [Python](https://www.python.org/) and most of its common libraries for scientits (numpy, matplotlib) and data science (pandas). Also experienced in web applications (html, javascript, ReactJS, CSS...) and SQL management with [SQLite](https://sqlite.org/index.html) and [MySQL](https://www.mysql.com/). Awarded with a [Developer Certification in Android Development with Java](http://bcert.me/sglpcwce) and interested in promissing languages like [Julia](https://julialang.org/).

  Firm defendant of [Open Source in Science and Technology](https://archive.org/stream/GuerillaOpenAccessManifesto/Goamjuly2008_djvu.txt).
# baseurl: "/" # the subpath of your site, e.g. /blog/
# url: "http://jekyll.github.io" # the base hostname & protocol for your site
github_username:  labay11

livereload: true

# Build settings
# markdown: kramdown
# mathjax: true

plugins:
  - "jekyll-github-metadata"
